# Defaults for image training.

attention_resolutions: "32,16,8"
class_cond: False
diffusion_steps: 25
image_size: 256
learn_sigma: True
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_res_blocks: 2
resblock_updown: True
use_fp16: False
use_scale_shift_norm: True
batch_size: 4
num_samples: 100
# timestep_respacing: 1000
model_path: D:\doingproject\DDNM\exp\logs\imagenet\256x256_diffusion_uncond.pt

# channel_mult: ""
# use_checkpoint: False
# num_heads: 4
# num_heads_upsample: -1
# dropout: 0.0
# use_new_attention_order: False

# classifier_scale: 1.0 
rescale_timesteps: True