seed_everything: 20
trainer:
  # deterministic: True
  # limit_train_batches: 100
  # limit_val_batches: 100
  enable_checkpointing: False
  devices: [0]  
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

  # precision: 16
  # profiler: simple
model:
  class_path: MODEL.LCMOS.MYmd.MYMD
  init_args:    
    train_batchsize: 16
    # val_batchsize: ${.train_batchsize}
    # test_batchsize: ${.train_batchsize}        
    val_batchsize: 1
    test_batchsize: 1        
    model: 
      class_path: MODEL.LCMOS.model.GDBC
      init_args:   
        snum: 3
        ema: 0.9 
        sth: 0.01    
        # encoder: MODEL.encoder.resnet  
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1.0e-4
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 50
    eta_min: 5.0e-7


